### ISSUE TITLE
Tabs can't be selected

### ISSUE THREAD

**Issue by Artur-** [vaadin/vaadin-tabs-flow#27]
1. `mvn jetty:run`
2. Open localhost:9998/vaadin-tabs in IE11, Edge or Firefox
3. Click on any tab in the "Tabs with pages" section.

The content is never updated

**Comment by Artur-** [comment]
Most likely caused by #25, which is not shown when in production mode because of https://github.com/vaadin/flow/issues/3524

**Comment by caalador** [comment]
Fixed by #25 
Verified with latest snapshot of Tabs.
