### ISSUE TITLE
DX test Tabs

### ISSUE THREAD

**Issue by torok-peter** [vaadin/vaadin-tabs-flow#4]
### Acceptance Criteria
- Run DX tests for `Tabs` and `ProgressBar` with minimum three candidates with the basic use cases (and any special ones if necessary), create document with notes and go through the notes and create issues on findings.
Issue for vaadin/vaadin-progress-bar-flow#4

**Comment by pleku** [comment]
With tabs you want to test the basic use cases for it, by creating an app with e.g. different grids for different tab contents.
