### ISSUE TITLE
selectionChange event not fired for automatically selected tabs

### ISSUE THREAD

**Issue by pleku** [vaadin/vaadin-tabs-flow#60]
@stefanuebe commented on [Thu Apr 19 2018](https://github.com/vaadin/flow/issues/3932)

I have a Tabs component and add multiple tabs. The selection change listener handles the lazy loading of the tab content, replacing the content are with it, etc.

Problem here is, that the first tab is marked as selected, but the selection change listener does not fire. This means that as user I'm forced to handle the content loading logic at two places (extract to method and so on). For simple cases maybe a little overhead.

The same issue occurs when Flow selects other tabs, after removing the current tab. For example I add 5 tabs, select the first 3 tabs - the content of Tab 4 and 5 is not loaded yet.
I select tab 3, remove this one (by a simple button). Flow now automatically selects tab 4, but does not fire the selection change event - with the result, that the content area is not loaded.

My request is, that adding the first tab or (more generalized) after automatic selection of a tab Flow should fire a selection change event, since the selection changed somehow. Optional there could be an additional boolean attribute in the event to indicate this initial selection like `isAutomaticSelection`

---

@denis-anisimov commented on [Sat Aug 04 2018](https://github.com/vaadin/flow/issues/3932#issuecomment-410459143)

If I understood you issue correctly then the scenario is:
- `Tabs`  with two `Tab`s  : `tab1` and `tab2`.
- `tab1` is selected.
- if you change selection from `tab1` to `tab2` then there is a selection event.
- Now if `tab1` is selected and you remove it then it disappears and `tab2` becomes selected visually on the client side but there is no selection event.

Is it right ?

Well, initially I thought this is a client side problem.
But then I've realized that on the client side there is no such thing as "selected tab".
There is only "selected index" and it hasn't been changed because it's the same as it was : `0`.

So looks like we should add some logic in the server side which checks component updates and fires selection event even though there is no any selection update from the client side.

---

@denis-anisimov commented on [Sun Aug 05 2018](https://github.com/vaadin/flow/issues/3932#issuecomment-410527898)

It turns out that we cannot listen changes in children list on the server side.
So the be able to fix this I've added a client-side listener for items changes.
The event will be fired in case of changes in items and then it will be forwarded to the server side which fires an event.
As a consequence the selection change event won't be fired right away on changes in the children list on the server side. Also if the component is not attached yet to the DOM tree then there will be no selection event.

**Comment by pleku** [comment]
>As a consequence the selection change event won't be fired right away on changes in the children list on the server side. Also if the component is not attached yet to the DOM tree then there will be no selection event.

This is a bit weird in terms of similar behavior in other components - usually when there is an event that can be triggered from both server & client side, the event is fired for both and there is a flag (eg. `isFromClient()` that can be used to eg. ignore server side changes. This is also the case for `SelectionChangeEvent` in `Tabs`, so I would presume that it should be fired also when some changes are made from server side, eg. when removing the selected tab. From what I've understood from #59, a servere side tabs removal will cause a server side event after a client roundtrip and have the `isFromClient` flag set to `true`, even though it should be `false` in this case.

I think it is a guideline for all of this type of server side driven changes that we should immediately:
- update the state on server side
- fire events with the correct flag
And not wait for the roundtrip.

**Comment by pleku** [comment]
I would expect the event to be fired on the removal of selected tab, thus I see this as a bug. Also the javadocs for the event could be improved to describe when it is actually fired, like this case https://github.com/vaadin/vaadin-tabs-flow/blob/master/src/main/java/com/vaadin/flow/component/tabs/Tabs.java#L88

**Comment by pekam** [comment]
#68 makes the component fire server-side events synchronously with the correct flag.

It also changes this behavior of changing the selected tab when adding/removing components. I considered it as a bug, because:
- It's unexpected. If I for example add a new tab to the beginning, why would the selected tab change?
- If I have selected the last tab and remove some earlier tabs, the selected index will be out of bounds.

Because of this I changed the behavior so that it doesn't change the selected tab on add/remove, except when the selected tab itself is removed.
